services:
  backend:
    build: ./backend
    container_name: finaceshelp_backend
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: finaceshelp_frontend
    ports:
      - "3000:80"
    restart: unless-stopped